//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class KindKala
    {
        public string Name { get; set; }
        public string MetrDarad { get; set; }
        public Nullable<long> Metr { get; set; }
        public string NameService { get; set; }
        public long Id { get; set; }
    }
}
