//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Access { get; set; }
        public long IdManage { get; set; }
        public string NewService { get; set; }
        public string Tools { get; set; }
        public string Search { get; set; }
        public string Sms { get; set; }
        public string Report { get; set; }
        public string Backup { get; set; }
        public string Setting { get; set; }
    }
}
