//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg
    {
        public long Id { get; set; }
        public string State { get; set; }
        public Nullable<long> Date { get; set; }
        public string Serial1 { get; set; }
        public Nullable<long> CountOpen { get; set; }
    }
}
