//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportService
    {
        public string Ready { get; set; }
        public string Eshterak { get; set; }
        public Nullable<long> Date { get; set; }
        public string Kind { get; set; }
        public string Kala { get; set; }
        public string Service { get; set; }
        public string Some { get; set; }
        public string Price { get; set; }
        public string CodeRahgiri { get; set; }
        public string NumberServise { get; set; }
        public long Id { get; set; }
    }
}
