//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesPrice
    {
        public string ServisKind { get; set; }
        public string ServiceKala { get; set; }
        public string ServiseName { get; set; }
        public Nullable<long> ServicePrice { get; set; }
        public long Id { get; set; }
    }
}
