//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public string Eshterak { get; set; }
        public string Name { get; set; }
        public Nullable<long> DateService { get; set; }
        public string Mobile { get; set; }
        public Nullable<long> Bestankar { get; set; }
        public Nullable<long> Pardakhti { get; set; }
        public Nullable<decimal> Takhfif { get; set; }
        public Nullable<long> SumServices { get; set; }
        public string Tasfiye { get; set; }
        public string CodeRahgiri { get; set; }
        public string NumberService { get; set; }
        public Nullable<long> ReadyDate { get; set; }
        public Nullable<long> SendReadySms { get; set; }
        public string Description { get; set; }
        public long IdService { get; set; }
    }
}
