//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string CommercialName { get; set; }
        public string ManageName { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Signature { get; set; }
        public string NumberSms { get; set; }
        public string GroupSms { get; set; }
        public string WelcomeSms { get; set; }
        public string AcceptSms { get; set; }
        public string ReadySms { get; set; }
        public string DeliverySms { get; set; }
        public string InviteClubeSms { get; set; }
        public string BirthDaySms { get; set; }
        public long Id { get; set; }
        public Nullable<long> EndCreateCodeRahgiri { get; set; }
    }
}
