//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Eshterak { get; set; }
        public string Name { get; set; }
        public Nullable<long> Date { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<long> BirthDayDate { get; set; }
        public string Address { get; set; }
        public string PostiCode { get; set; }
        public long Id { get; set; }
    }
}
